<?php

namespace Paymentsds\MPesa;

class ErrorType
{
    const SUCCESS = 'SUCCESS';
    const INTERNAL_ERROR = 'INTERNAL_ERROR';
    const TRANSACTION_CANCELLED_BY_CUSTOMER = 'TRANSACTION_CANCELLED_BY_CUSTOMER';
    const TRANSACTION_FAILED = 'TRANSACTION_FAILED';
    const REQUEST_TIMEOUT = 'REQUEST_TIMEOUT';
    const DUPLICATE_TRANSACTION = 'DUPLICATE_TRANSACTION';
    const INVALID_SHORT_CODE_USED = 'INVALID_SHORT_CODE_USED';
    const INVALID_REFERENCE_USED = 'INVALID_REFERENCE_USED';
    const INVALID_AMOUNT_USED = 'INVALID_AMOUNT_USED';
    const SERVER_UNDER_OVERLOAD = 'SERVER_UNDER_OVERLOAD';
    const INVALID_TRANSACTION_REFERENCE = 'INVALID_TRANSACTION_REFERENCE';
    const INVALID_TRANSACTION = 'INVALID_TRANSACTION';
    const INVALID_REFERENCE = 'INVALID_REFERENCE';
    const MISSING_PROPERTIES = 'MISSING_PROPERTIES';
    const INVALID_PARAMETERS = 'INVALID_PARAMETERS';
    const INVALID_OPERATION_TYPE = 'INVALID_OPERATION_TYPE';
    const UNKOWN_STATUS = 'UNKOWN_STATUS';
    const INVALID_INITIATOR_IDENTIFIER = 'INVALID_INITIATOR_IDENTIFIER';
    const INVALID_SECURITY_CREDENTIAL = 'INVALID_SECURITY_CREDENTIAL';
    const DIRECT_DEBIT_MISSING = 'DIRECT_DEBIT_MISSING';
    const DIRECT_DEBIT_ALREAD_EXISTS = 'DIRECT_DEBIT_ALREAD_EXISTS';
    const CUSTOMER_HAS_PROBLEMS = 'CUSTOMER_HAS_PROBLEMS';
    const CUSTOMER_ACCOUNT_NOT_ACTIVE = 'CUSTOMER_ACCOUNT_NOT_ACTIVE';
    const UNKNOWN = 'UNKNOWN';
    const INVALID_MARKET = 'INVALID_MARKET';
    const INITIATOR_AUTH_ERROR = 'INITIATOR_AUTH_ERROR';
    const RECEIVER_INVALID = 'RECEIVER_INVALID';
    const INSUFICIENT_BALANCE = 'INSUFICIENT_BALANCE';
    const INVALID_MSISDN = 'INVALID_MSISDN';
    const LANGUAGE_CODE_INVALID = 'LANGUAGE_CODE_INVALID';
    const INVALID_RECEIVER = 'INVALID_RECEIVER';
    
    const INVALID_INPUT = 'INVALID_INPUT';
    const MISSING_INPUT = 'MISSING_INPUT';
    const UNAUTHORIZED_API_OR_SESSION = 'UNAUTHORIZED_API_OR_SESSION';
}
